DEPARTMENTS = [
    "NWC",
    "DSBS",
    "CNS",
    "CINTEL",
    "CTECH",
    "ECE",
    "EEE",
    "MECH",
    "CIVIL",
    "IT",
    "AIML",
    "AIDS",
    "SCOPE",
    "Maths",
    "Physics",
    "Chemistry",
]


SPECIALIZATIONS = [
    "NWC (Networking & Communications)",
    "Computer Science and Engineering (Network & Communications)",
    "DSBS (Data Science & Business Systems)",
    "Computer Science and Engineering (Data Science & Business Systems)",
    "CNS (Cyber Security)",
    "Computer Science and Engineering (Cyber Security)",
    "CINTEL (Intelligent Systems)",
    "Computer Science and Engineering (Artificial Intelligence & Machine Learning)",
    "CTECH (Core CSE)",
    "Computer Science and Engineering (Core)",
    "Artificial Intelligence & Machine Learning (AIML)",
    "Artificial Intelligence & Data Science (AIDS)",
    "Big Data Analytics",
    "Cloud Computing",
    "Internet of Things (IoT)",
    "Blockchain Technology",
    "Electronics and Communication Engineering (ECE)",
    "Electronics and Computer Engineering",
    "VLSI Design",
    "Electrical and Electronics Engineering (EEE)",
    "Mechanical Engineering",
    "Mechatronics Engineering",
    "Civil Engineering",
    "Information Technology",
    "Mathematics",
    "Physics",
    "Chemistry",
]
